camera:
  image_projection:
    ros__parameters:
      camera:
        extrinsic_camera_calibration:
          top_x: 144
          top_y: 41
          bottom_x: 326
          bottom_y: 129
          offset_x: -45     
          offset_y: 160      
