/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_l: 0
          hue_h: 163
          saturation_l: 0
          saturation_h: 58
          lightness_l: 195
          lightness_h: 255
          
        yellow:
          hue_l: 0
          hue_h: 65
          saturation_l: 62
          saturation_h: 255
          lightness_l: 142
          lightness_h: 255

